### ISSUE TITLE
Pagination sometimes not working on filtered PaginatedList

### ISSUE THREAD

**Issue by fvln** [jschomay/elm-paginate#10] opened 2020-09-03 08:21 UTC
Hi,

There is an issue with the way the `currentPage_` is stored within a PaginatedList, in particular when displaying a filtered paginated list. 

### How to reproduce, on the example page: https://jschomay.github.io/elm-paginate/

1. Click on the `>>` button to display the last (4th) page
2. In the Search bar, type '2'. only 13 items are displayed now
3. Click on `<`, nothing happens the first 2 times

This is because the `currentPage_` integer from the `things` paginated list is set to 4, and it seems the `filteredSortedThings` paginated list inherits this value, although there are only 2 pages available in the filtered list.

A workaround would be to call `Paginate.next` on the _filtered_ list instead of the _things_ list, but I'm not sure it's the proper way to do this.

**Comment by jschomay** [comment] 2020-09-03 15:51
Hi, good find, thank you for sharing.  I'll try to look into it this weekend and get back to you.

**Comment by jschomay** [comment] 2020-09-09 15:39
I've had a chance to look a little closer.  Again, great find.

The issue is in how the example works, not the library itself.  The `currentPage_` properly gets set when the size of the list changes upon filtering.  You can see this in in the example view (page 2 is bold, meaning it is the current page).  The problem is that the list is sorted and filtered only at the view level.  When pressing `<` it sends the `Prev` message, which in turn calls `Paginate.prev` on `model.things`, which doesn't have the sorting that is done in the view layer.

There are a couple solutions to solve this discrepancy between the view and model layers, though none of them are as clean as I would like:

1. Store the filtered list in the model instead of doing it dynamically in the view.  This isn't great because you will lose the original unfiltered list.  If you store the original list in the model to restore later, you lose the benefits of the library and have to handle syncing manually if the original list changes.  So this probably isn't a good approach.

2. Change the click handlers on the `<`/`>`/`>>` buttons to use `Goto` with the correctly calculated index based on the filtered list.  For example: 

        button [ onClick (Goto <| Paginate.currentPage <| Paginate.prev filteredSortedThings ] [ text "<" ]

3. Avoid the problem all together by setting `model.things` to the first page whenever `query` changes.  This way you can't get out of sync between the model and view because `>` would be disabled when you reach the end of the paginated filtered list.  You would have to change the `>>` button to work more like the approach above though, or you would end up in the buggy state again.

I can't think of any other better solutions right now.  Let me know if any of those suggestions would work for you.  Since I see this as an issue with the client functionality rather than the library functionality, I'm going to close this issue, but feel free to open it again if you aren't satisfied.  Also, if you try some of the above solutions and find one you like, make a PR to fix the example and I'll merge it.

Thanks again!

**Closed as completed by jschomay** 2020-09-09 15:39 UTC

**Comment by fvln** [comment] 2020-09-10 20:35
Hi Jeff, 

Thanks for having a look at this issue. The first workaround I thought about would have been to store both the original and the filtered list in my model, which is not optimal regarding memory usage; and as you mentioned I would lose the auto sync between these lists.

Solution 3 would totally work for me since it's not illogical to be brought back to the first page whenever `query` changes, and I also like the clever approach you had in point 2, so I'm think I will be going with the latter.

I'll try to submit a PR on the example next week after some testing, thanks again for your help!
